SELECT * FROM ZOOKEEPER;
SELECT * FROM ANIMAL;
SELECT * FROM HANDLES;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE REGEXP_LIKE (SSN, '^[0-9]{3}-[0-9]{2}-[0-9]{4}$');

SELECT * FROM EMPLOYEE
WHERE length(Fname) = 5;